### PR TITLE
fix: prepare withMask function to React 19 ref breaking changes

### PR DESCRIPTION
**Pull request by adrianorocha-dev**
I updated the withMask function in order to prepare it to the upcoming React 19 breaking changes on refs.
More info on https://react.dev/blog/2024/04/25/react-19#cleanup-functions-for-refs.

### CODE REVIEW

**Comment by eduardoborges** [comment]
Nice! Can you provide some evidences with React 17 and 18?

**Comment by adrianorocha-dev** [comment]
Here is evidence of the library correctly working with React 17, 18, and 19:

https://github.com/eduardoborges/use-mask-input/assets/17671035/94d70612-b83c-448c-9dd4-1f5c7059dff4


https://github.com/eduardoborges/use-mask-input/assets/17671035/8a2dcd31-8735-41b7-9e2d-fdcbf7df8715


https://github.com/eduardoborges/use-mask-input/assets/17671035/e4de946c-dab7-41aa-82b9-1ec7bfd88877

**Review by eduardoborges — APPROVED** [review]
LGTM

**Pull request merged**
